# With okta-spring-boot-starter
okta:
  oauth2:
    issuer: https://lafeuille-dev-eu.eu.auth0.com/
    audience: https://demo-auth0-security.lafeuille.org
# Or with spring-boot-starter-oauth2-resource-server
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lafeuille-dev-eu.eu.auth0.com/
          audiences: https://demo-auth0-security.lafeuille.org